name: Swift
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
defaults:
  run:
    working-directory: Example
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: linting
        run: swiftlint lint
  example-app-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Example app Unit and UI testing -> iPhone 11 (iOS 14.3)
        run: xcodebuild test -scheme ConsentViewController_Example -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
  native-app-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: NativeMessage UI testing -> iPhone 11 (iOS 14.3)
        run: xcodebuild test -scheme NativeMessageExample -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
  meta-app-tests:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: SourcePointMetaApp UI testing -> iPhone 11 (iOS 14.3)
          run: xcodebuild clean test -scheme SourcePointMetaApp -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
  auth-app-tests:
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@v2
      - name: AuthExampe App UI testing -> iPhone 11 (iOS 14.3)
        run: xcodebuild test -scheme AuthExample -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
  objc-example-app-tests:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: ObjC-ExampleApp UI testing -> iPhone 11 (iOS 14.3)
          run: xcodebuild clean test -scheme ObjC-ExampleApp -workspace ConsentViewController.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

