name: SwiftLint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint: 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: installing swiftlint
        run: brew install swiftlint
      - name: linting
        run: cd Example && swiftlint lint
